[package]
name = "defund"
version = "1.0.0"
authors = ["MR"]

[addresses]
std = "0x1"
defund = "0x82bb6290772ce549f0f250b2893c677baa0d1e93cd6706b6f90b55aa843c713f"
aptos_framework = "0x1"
aptos_std = "0x1"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "main"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
