[package]
name = "de_objectbox"
version = "1.0.0"
authors = ["MR"]

[addresses]
std = "0x1"
de_objectbox = "0x42"
aptos_framework = "0x1"
aptos_std = "0x1"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "main"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
